FROM golang:rc-stretch

# Install extra packages + gometalinter
RUN apt-get update && \
  apt-get install -y bash libc6-dev gcc git && \
  rm -rf /var/lib/apt/lists/* && \
  cd /usr/local && \
  wget -O - https://git.io/vp6lP | sh
